env: dev
application:
  name: dsl-service-app
  group-id: service.group.1
  port: 8000
slb:
  host: http://127.0.0.1:8761/ #这个slb和微服务的服务发现地址一致
  port: 8761
  interval: 30  #心跳间隔时间 单位s
log:
  level: debug
  path: /usr/local/dsl/dev.log
remote:
  host: http://127.0.0.1